### ISSUE TITLE
Project layout

### ISSUE THREAD

**Issue by FranOis** [jelmersnoeck/aiven#5]
According to my recent googling on how to manage go projects (I'm new to go). It seems like it all code under package aiven should be under a `aiven` directory. I do believe this would also be very helpful to cleanup a bit the code and separate code from config/readme etc.

**Comment by jelmersnoeck** [comment]
For a package like this, it's actually fine to have it as is. The package is "aiven", under `github.com/jelmersnoeck/aiven`. Having it under a subdirectory `aiven` again would just duplicate that.

Extra sub-packages could be useful when the codebase becomes larger, but I feel like this is still manageable for now.
